"""add location to job_postings

Revision ID: 67f53bcfe1c0
Revises: 699fe6166ebf
Create Date: 2026-07-27 19:47:44.145508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f53bcfe1c0'
down_revision: Union[str, Sequence[str], None] = '699fe6166ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('location', sa.Enum('ON_SITE', 'HYBRID', 'REMOTE', name='joblocation', native_enum=False, length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'location')
    # ### end Alembic commands ###
